Using custom data configuration default-280267f50cc0f57f
Found cached dataset csv (/home/nlplab12/.cache/huggingface/datasets/csv/default-280267f50cc0f57f/0.0.0/6b34fb8fcf56f7c8ba51dc895bfa2bfbe43546f190a60fcf74bb5e8afdcc2317)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 922.94it/s]
35000
Some weights of the model checkpoint at monologg/koelectra-base-v3-discriminator were not used when initializing ElectraForSequenceClassification: ['discriminator_predictions.dense_prediction.weight', 'discriminator_predictions.dense.weight', 'discriminator_predictions.dense_prediction.bias', 'discriminator_predictions.dense.bias']
- This IS expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at monologg/koelectra-base-v3-discriminator and are newly initialized: ['classifier.out_proj.bias', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loading cached processed dataset at /home/nlplab12/.cache/huggingface/datasets/csv/default-280267f50cc0f57f/0.0.0/6b34fb8fcf56f7c8ba51dc895bfa2bfbe43546f190a60fcf74bb5e8afdcc2317/cache-3e775a62ad91b9dd.arrow
Loading cached processed dataset at /home/nlplab12/.cache/huggingface/datasets/csv/default-280267f50cc0f57f/0.0.0/6b34fb8fcf56f7c8ba51dc895bfa2bfbe43546f190a60fcf74bb5e8afdcc2317/cache-11d7db9c3b04ecf5.arrow
Loading cached shuffled indices for dataset at /home/nlplab12/.cache/huggingface/datasets/csv/default-280267f50cc0f57f/0.0.0/6b34fb8fcf56f7c8ba51dc895bfa2bfbe43546f190a60fcf74bb5e8afdcc2317/cache-8cede8cc0cfff179.arrow
Loading cached shuffled indices for dataset at /home/nlplab12/.cache/huggingface/datasets/csv/default-280267f50cc0f57f/0.0.0/6b34fb8fcf56f7c8ba51dc895bfa2bfbe43546f190a60fcf74bb5e8afdcc2317/cache-9cd6f25650974ace.arrow
{'Unnamed: 0': 0, 'document': '굳', 'label': 1}
512
Traceback (most recent call last):
  File "naver_classification.py", line 64, in <module>
    train_dataset=train_dataset.to(device),
AttributeError: 'Dataset' object has no attribute 'to'
Traceback (most recent call last):
  File "naver_classification.py", line 64, in <module>
    train_dataset=train_dataset.to(device),
AttributeError: 'Dataset' object has no attribute 'to'